import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      };

      serve(async (req: Request) => {
        if (req.method === 'OPTIONS') {
            return new Response('ok', { headers: corsHeaders });
              }

                if (req.method !== 'POST') {
                    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
                          status: 405,
                                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                    });
                                      }

                                        try {
                                            const body = await req.json();
                                                console.log('[fault-alert] Received payload:', JSON.stringify(body));

                                                    const { vehicle_reg, driver_id, faults, inspection_id, invoice_no, notes } = body;

                                                        if (!vehicle_reg || !Array.isArray(faults) || faults.length === 0) {
                                                              return new Response(JSON.stringify({ error: 'vehicle_reg and faults array are required' }), {
                                                                      status: 400,
                                                                              headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                    });
                                                                                        }

                                                                                            const resendApiKey = Deno.env.get('RESEND_API_KEY') ?? '';
                                                                                                if (!resendApiKey) {
                                                                                                      console.error('[fault-alert] RESEND_API_KEY is missing');
                                                                                                            return new Response(JSON.stringify({ error: 'Resend API key not configured' }), {
                                                                                                                    status: 500,
                                                                                                                            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                  });
                                                                                                                                      }

                                                                                                                                          const adminEmailRaw = Deno.env.get('ADMIN_EMAIL') ?? '';
                                                                                                                                              const toEmails = adminEmailRaw.split(',').map(e => e.trim()).filter(Boolean);
                                                                                                                                                  if (toEmails.length === 0) {
                                                                                                                                                        toEmails.push('reeqieric41@gmail.com');
                                                                                                                                                            }

                                                                                                                                                                console.log('[fault-alert] Sending to:', toEmails);

                                                                                                                                                                    const fromEmail = Deno.env.get('SENDER_EMAIL') ?? 
                                                                                                                                                                                         Deno.env.get('FROM_EMAIL') ?? 
                                                                                                                                                                                                              'Inyathi Alerts <onboarding@resend.dev>';

                                                                                                                                                                                                                  const timestamp = new Date().toLocaleString('en-ZA', { timeZone: 'Africa/Johannesburg' });

                                                                                                                                                                                                                      const faultListText = faults
                                                                                                                                                                                                                            .map((f: string, i: number) => `${i + 1}. ${f}`)
                                                                                                                                                                                                                                  .join('\n');

                                                                                                                                                                                                                                      const rawText = `🚨 CRITICAL FAULT ALERT — INYATHI 🚨\n\n` +
                                                                                                                                                                                                                                            `Vehicle: ${vehicle_reg}\n` +
                                                                                                                                                                                                                                                  `Driver ID: ${driver_id ?? 'N/A'}\n` +
                                                                                                                                                                                                                                                        `Time: ${timestamp}\n` +
                                                                                                                                                                                                                                                              `Booking: ${invoice_no ?? 'N/A'}\n\n` +
                                                                                                                                                                                                                                                                    `Faults:\n${faultListText}\n\n` +
                                                                                                                                                                                                                                                                          (notes ? `Notes: ${notes}\n\n` : '') +
                                                                                                                                                                                                                                                                                `Action required: Vehicle must be inspected before next trip.`;

                                                                                                                                                                                                                                                                                    console.log('[fault-alert] Sending email via Resend...');

                                                                                                                                                                                                                                                                                        const resendResponse = await fetch('https://api.resend.com/emails', {
                                                                                                                                                                                                                                                                                              method: 'POST',
                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                            'Authorization': `Bearer ${resendApiKey}`,
                                                                                                                                                                                                                                                                                                                    'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                        from: fromEmail,
                                                                                                                                                                                                                                                                                                                                                to: toEmails,
                                                                                                                                                                                                                                                                                                                                                        subject: `🚨 CRITICAL FAULT ALERT: ${vehicle_reg}`,
                                                                                                                                                                                                                                                                                                                                                                text: rawText,
                                                                                                                                                                                                                                                                                                                                                                      }),
                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                              const responseData = await resendResponse.json();

                                                                                                                                                                                                                                                                                                                                                                                  console.log('[fault-alert] Resend API Response:', {
                                                                                                                                                                                                                                                                                                                                                                                        status: resendResponse.status,
                                                                                                                                                                                                                                                                                                                                                                                              ok: resendResponse.ok,
                                                                                                                                                                                                                                                                                                                                                                                                    data: responseData
                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                            const success = resendResponse.ok;

                                                                                                                                                                                                                                                                                                                                                                                                                if (success && inspection_id) {
                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                              const adminClient = createClient(
                                                                                                                                                                                                                                                                                                                                                                                                                                        Deno.env.get('SUPABASE_URL') ?? '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await adminClient.from('inspections').update({ alert_sent: true }).eq('id', inspection_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('[fault-alert] Updated inspection alert_sent flag');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (dbError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('[fault-alert] DB update failed:', dbError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response(JSON.stringify({ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  resend_status: resendResponse.status 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const message = error instanceof Error ? error.message : String(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('[fault-alert] Error:', message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(JSON.stringify({ error: message }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });